yizhitong/workerlib-ui

src/common/HttpClient.ts
src/components/Login.vue
src/store/modules/LoginStore.ts
src/views/login.pug

Modified   src/components/Login.vue
Modified   src/store/modules/LoginStore.ts
Modified   src/views/login.pug

Modified   src/common/HttpClient.ts

---

src/components/Contributive.vue
src/components/Nav.vue
src/store/modules/CommentsStore.ts
src/store/modules/WorkerStore.js
src/store/modules/WorkerStore.ts
src/styles/contributive.css
src/views/contributive.pug

已修改        src/components/Nav.vue
已修改        src/store/modules/CommentsStore.ts
已修改        src/store/modules/WorkerStore.js
已修改        src/styles/contributive.css
已修改        src/views/contributive.pug
已修改        src/components/Contributive.vue

2019-11-01 14:19

---

src/styles/home.css
src/views/home.pug

Modified   src/styles/home.css

---

src/assets/css/common.css
src/styles/worker.css
src/views/worker.pug

Modified   src/styles/worker.css
Modified   src/views/worker.pug

Modified   src/assets/css/common.css

---

src/styles/worker.css
src/views/worker.pug

Modified   src/views/worker.pug

Modified   src/styles/worker.css

---

CodeGenerator.js
package/webpack.build.conf.js
src/common/HttpClient.ts
src/components/Login/Index.vue
src/components/Nav/Project/Index.vue
src/components/Nav/Unit/Index.vue
src/store/modules/ProjectStore.ts
src/store/modules/UnitStore.ts
src/styles/project.css
src/views/project.pug
src/views/unit.pug

已修改        package/webpack.build.conf.js
已修改        src/common/HttpClient.ts
已修改        src/components/Login/Index.vue
已修改        src/components/Nav/Unit/Index.vue
已修改        src/store/modules/UnitStore.ts
已修改        src/styles/project.css
已修改        src/views/unit.pug

已添加        CodeGenerator.js

---

codeGenerator.js
src/common/MessageUtils.ts
src/views/home.pug
src/views/nav.pug

Modified   src/views/home.pug
Modified   src/views/nav.pug
Add        src/common/MessageUtils.ts

Modified   codeGenerator.js

---

src/components/Nav/Courseware/Index.vue
src/components/Nav/Home/Index.vue
src/components/Nav/Lecturer/Index.vue
src/components/Nav/Project/Index.vue
src/components/Nav/Unit/Index.vue
src/components/Nav/Worker/Index.vue
src/store/modules/LecturerStore.ts
src/store/modules/ProjectStore.ts
src/store/modules/UnitStore.ts
src/store/modules/WorkerStore.ts
src/styles/courseware.css
src/styles/home.css
src/styles/lecturer.css
src/styles/project.css
src/styles/unit.css
src/styles/worker.css
src/views/account.pug
src/views/courseware.pug
src/views/home.pug
src/views/lecturer.pug
src/views/project.pug
src/views/unit.pug
src/views/workclass.pug
src/views/worker.pug

已修改        src/components/Nav/Unit/Index.vue
已修改        src/components/Nav/Worker/Index.vue
已修改        src/store/modules/UnitStore.ts
已修改        src/styles/home.css
已修改        src/styles/project.css
已修改        src/styles/unit.css
已修改        src/styles/worker.css
已修改        src/views/home.pug
已修改        src/views/unit.pug
已修改        src/views/worker.pug

已修改        src/components/Nav/Home/Index.vue

---

src/common/HttpClient.ts
src/components/Nav/Courseware/Index.vue
src/components/Nav/Lecturer/Index.vue
src/components/Nav/Project/Index.vue
src/components/Nav/Unit/Index.vue
src/components/Nav/Worker/Index.vue
src/store/modules/CheckEvaluateStore.ts
src/store/modules/CoursewareStore.ts
src/store/modules/LoginStore.ts
src/store/modules/ProjectStore.ts
src/store/modules/UnitStore.ts
src/store/modules/WorkerStore.ts
src/styles/courseware.css
src/styles/worker.css
src/views/courseware.pug
src/views/nav.pug
src/views/project.pug
src/views/spectaculars.pug
src/views/unit.pug
src/views/worker.pug

已修改        src/components/Nav/Courseware/Index.vue
已修改        src/components/Nav/Lecturer/Index.vue
已修改        src/components/Nav/Unit/Index.vue
已修改        src/components/Nav/Worker/Index.vue
已修改        src/store/modules/CheckEvaluateStore.ts
已修改        src/store/modules/CoursewareStore.ts
已修改        src/store/modules/LoginStore.ts
已修改        src/store/modules/UnitStore.ts
已修改        src/styles/courseware.css
已修改        src/styles/worker.css
已修改        src/views/courseware.pug
已修改        src/views/nav.pug
已修改        src/views/spectaculars.pug
已修改        src/views/unit.pug
已修改        src/views/worker.pug

已修改        src/common/HttpClient.ts

---

package.json
src/common/HttpClient.ts
src/components/Nav/Account/Index.vue
src/components/Nav/TurnWork/Index.vue
src/store/modules/AccountStore.ts
src/views/account.pug

给增加账户页面加了角色和项目的下拉框并实现了多选和增加的功能

src\components\Nav\Account\Index.vue

---

src/common/HttpClient.ts
src/components/Nav/Comments/Index.vue
src/store/modules/CommentsStore.ts
src/store/modules/WorkerStore.ts
src/styles/comments.css
src/views/comments.pug

已修改        src/common/HttpClient.ts
已修改        src/components/Nav/Comments/Index.vue
已修改        src/store/modules/CommentsStore.ts
已修改        src/styles/comments.css
已修改        src/views/comments.pug

已删除        package.json

---

src/components/Nav/Nav.vue
src/store/modules/AccountStore.ts
src/store/modules/CheckEvaluateStore.ts
src/store/modules/CommentsStore.ts
src/store/modules/CourseStore.ts
src/store/modules/EvaluationStore.ts
src/store/modules/LoginStore.ts
src/store/modules/OptionsStore.ts
src/store/modules/PunishmentStore.ts
src/store/modules/RoleStore.ts
src/store/modules/SpectacularsStore.ts
src/store/modules/WorkclassStore.ts

Modified   src/store/modules/AccountStore.ts
Modified   src/store/modules/CheckEvaluateStore.ts
Modified   src/store/modules/CommentsStore.ts
Modified   src/store/modules/CourseStore.ts
Modified   src/store/modules/EvaluationStore.ts
Modified   src/store/modules/LoginStore.ts
Modified   src/store/modules/OptionsStore.ts
Modified   src/store/modules/PunishmentStore.ts
Modified   src/store/modules/RoleStore.ts
Modified   src/store/modules/SpectacularsStore.ts
Modified   src/store/modules/WorkclassStore.ts

Modified   src/components/Nav/Nav.vue

---

src/components/Nav/Comments/Index.vue
src/components/Nav/Project/Index.vue
src/store/modules/CommentsStore.ts
src/store/modules/ProjectStore.ts
src/store/modules/UnitStore.ts
src/store/modules/WorkerStore.ts
src/styles/comments.css
src/views/comments.pug
src/views/project.pug
src/views/worker.pug

已修改        src/store/modules/CommentsStore.ts
已修改        src/store/modules/UnitStore.ts
已修改        src/styles/comments.css
已修改        src/views/comments.pug
已修改        src/views/worker.pug

已修改        src/components/Nav/Comments/Index.vue

---

src/components/Nav/Project/Index.vue
src/store/modules/ProjectStore.ts
src/views/project.pug

已修改        src/components/Nav/Project/Index.vue

---

config/index.js
package.json
package/vue-loader.conf.js
package/webpack.build.conf.js
package/webpack.watch.conf.js

Modified   package.json
Modified   package/vue-loader.conf.js
Modified   package/webpack.build.conf.js
Modified   package/webpack.watch.conf.js

Modified   config/index.js

---

src/common/HttpClient.ts
src/components/Nav/Account/Index.vue
src/components/Nav/CheckEvaluate/Index.vue
src/components/Nav/Contributive/Index.vue
src/components/Nav/Courseware/Index.vue
src/components/Nav/Cultivate/Index.vue
src/components/Nav/Evaluation/Index.vue
src/components/Nav/IndexVideo/Index.vue
src/components/Nav/Project/Index.vue
src/components/Nav/Role/Index.vue
src/components/Nav/Unit/Index.vue
src/config/loadurls.json
src/store/modules/CheckEvaluateStore.ts
src/store/modules/CommentsStore.ts
src/store/modules/ProjectStore.ts
src/store/modules/WorkerStore.ts
src/styles/worker.css
src/views/checkevaluate.pug
src/views/lecturer.pug
src/views/nav.pug
src/views/spectaculars.pug
typings.d.ts

已修改        src/store/modules/CheckEvaluateStore.ts
已修改        src/styles/worker.css
已修改        src/views/checkevaluate.pug

已修改        src/components/Nav/CheckEvaluate/Index.vue

---

src/components/Mobile/Play/index.vue
src/components/Nav/Lecturer/Index.vue
src/store/mobile/PlayStore.ts
src/store/modules/LecturerStore.ts
src/styles/mobile/play.css
src/views/lecturer.pug
src/views/mobile/play.pug

已修改        src/store/modules/LecturerStore.ts
已修改        src/views/lecturer.pug
Add        src/components/Mobile/Play/index.vue
Add        src/store/mobile/PlayStore.ts
Add        src/styles/mobile/play.css
Add        src/views/mobile/play.pug

已修改        src/components/Nav/Lecturer/Index.vue

---

package.json
src/common/HttpClient.ts
src/components/Nav/Courseware/Index.vue
src/components/Nav/Nav.vue
src/components/Nav/Worker/Index.vue
src/config/loadurls.json
src/store/modules/CheckEvaluateStore.ts
src/store/modules/CoursewareStore.ts
src/store/modules/WorkerStore.ts
src/views/checkevaluate.pug
src/views/comments.pug
src/views/courseware.pug
src/views/nav.pug
src/views/worker.pug

Modified   src/common/HttpClient.ts
Modified   src/components/Nav/Courseware/Index.vue
Modified   src/components/Nav/Nav.vue
Modified   src/components/Nav/Worker/Index.vue
Modified   src/config/loadurls.json
Modified   src/store/modules/CheckEvaluateStore.ts
Modified   src/store/modules/CoursewareStore.ts
Modified   src/store/modules/WorkerStore.ts
Modified   src/views/checkevaluate.pug
Modified   src/views/comments.pug
Modified   src/views/courseware.pug
Modified   src/views/nav.pug
Modified   src/views/worker.pug

Modified   package.json

---

src/components/Mobile/Details/index.vue
src/components/Mobile/Play/index.vue
src/store/mobile/MobileStore.ts
src/store/modules/ProjectStore.ts
src/store/modules/UnitStore.ts
src/store/modules/WorkerStore.ts
src/views/mobile/details.pug

Modified   src/main/java/yizhit/workerlib/controllers/AlluserController.java
Modified   src/main/java/yizhit/workerlib/controllers/ArchivesController.java
Modified   src/main/java/yizhit/workerlib/controllers/ProjectController.java
Modified   src/main/java/yizhit/workerlib/controllers/UnitInfoController.java
Modified   src/main/java/yizhit/workerlib/excel/controller/ExcleController.java
Modified   src/main/java/yizhit/workerlib/excel/util/ExceclListener.java
Modified   src/main/resources/quartz-config.xml

Modified   .gitignore

---

src/store/modules/ContributiveStore.ts
src/store/modules/ProjectStore.ts
src/store/modules/UnitStore.ts
src/store/modules/WorkerStore.ts

Modified   src/store/modules/ProjectStore.ts
Modified   src/store/modules/UnitStore.ts
Modified   src/store/modules/WorkerStore.ts

Modified   src/store/modules/ContributiveStore.ts

---

src/views/login.pug
src/views/mobile/moveLogin.pug

已修改        src/views/mobile/moveLogin.pug

已修改        src/views/login.pug

---

src/components/Nav/Worker/Index.vue
src/styles/worker.css
src/views/nav.pug
src/views/worker.pug

已修改        src/styles/worker.css
已修改        src/views/nav.pug
已修改        src/views/worker.pug

已修改        src/components/Nav/Worker/Index.vue

---

src/common/components/IGrid.vue
src/components/Nav/BadList/Index.vue
src/views/nav.pug

Added      src/components/Nav/BadList/Index.vue
Modified   src/views/nav.pug

Added      src/common/components/IGrid.vue

---

package.json
src/App.vue
src/common/components/IGrid.vue
src/components/Mobile/Play/index.vue
src/components/Nav/Nav.vue
src/components/Nav/Project/Index.vue
src/store/mobile/PlayStore.ts
src/store/modules/ProjectStore.ts
src/styles/project.css
src/views/nav.pug
src/views/project.pug
yarn.lock

已修改        src/App.vue
已修改        src/common/components/IGrid.vue
已修改        src/components/Mobile/Play/index.vue
已修改        src/components/Nav/Nav.vue
已修改        src/store/mobile/PlayStore.ts
已修改        src/styles/project.css
已修改        src/views/nav.pug
已修改        yarn.lock

已修改        package.json
